servo/string-cache

macros/src/atom/mod.rs, macros/src/lib.rs, shared/repr.rs, src/atom/bench.rs, src/atom/mod.rs, src/event.rs, src/lib.rs, src/namespace.rs
* Macro syntax changed (mandatory closing semicolon).
* Array sytanx changed (`[ty, ..n]` replaced by `[ty; n]`).
* Enums became namespaced.
* `proc()` syntax got replaced by `move ||`.
* `#[deriving(x)]` became deprected and got replaced by `#[derive(x)]`.
* Some APIs changed (around pointers, slices, vectors, hashes, locks, strings, threads).
=> Update to build with latest rustc nightly

macros/src/atom/mod.rs, shared/repr.rs, src/atom/mod.rs
=> Fix deprecated stuff so it builds again

.travis.yml, README.md, macros/src/lib.rs, shared/repr.rs, src/atom/bench.rs, src/atom/mod.rs, src/event.rs, src/lib.rs, src/namespace.rs
=> Rustup and add Travis

examples/event-log/Cargo.toml, examples/summarize-events/Cargo.toml, src/atom/mod.rs
This makes it build again, but it have no idea what I’m doing. Please review for memory safety.
libcore now has ` impl<T> !Send for *mut T { }`, which might be what causes:
```
src/atom/mod.rs:59:1: 59:42 error: conflicting implementations for trait `core::marker::Send` [E0119]
src/atom/mod.rs:59 unsafe impl Send for *mut StringCacheEntry { }
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/atom/mod.rs:59:1: 59:42 note: conflicting implementation in crate `core`
src/atom/mod.rs:59 unsafe impl Send for *mut StringCacheEntry { }
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> Upgrade to rustc 1.0.0-nightly (4db0b3246 2015-02-25) (built 2015-02-26)

.travis.yml, examples/summarize-events/Cargo.toml, examples/summarize-events/src/main.rs, plugin/src/lib.rs, shared/lib.rs, src/lib.rs
It’s <s>probably going away</s> gone: https://github.com/rust-lang/rfcs/pull/1096
=> Remove usage of #[static_assert]

Cargo.toml
I need this in a released version:
https://github.com/servo/string-cache/pull/90
=> Bump version: 0.1.4 -> 0.1.5

.travis.yml, Cargo.toml, src/atom/mod.rs, src/lib.rs, src/namespace.rs
Part of servo/heapsize#5.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/105)
=> derive(HeapSizeOf).

Cargo.toml, build.rs, plugin/Cargo.toml, plugin/src/atom/mod.rs, shared/Cargo.toml, shared/build.rs, shared/lib.rs, shared/static_atom_list.rs, src/atom/mod.rs
<s>Do not merge yet.</s> This depends on https://github.com/sfackler/rust-phf/pull/62
Use the `phf_shared` and `phf_generator` crates directly instead of `phf`. This allows us to re-use the phf hash in the dynamic table and avoid hashing the same string again.
Also remove the indirection of `phf::OrderedSet` compared to `phf::Set`: we don’t care about the order, only about getting numeric indices. (The optimization mentioned in a comment of using a bit map of the first 64 atoms in the html5ever tree builder was never implemented. If we want it, the indirection and order preservation can be added back while preserving the hash reuse.)
Fixes #38.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/103)
=> Reuse phf hash and remove phf::OrderedSet indirection

shared/static_atom_list.rs
Added "*" to the list of constant atoms. It's used in getElementsByTagName and getElementsByTagNameNS in https://github.com/asajeffrey/servo/tree/versioned_dom.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/115)
=> Added "*" atom.

Cargo.toml, shared/static_atom_list.rs
Necessary for https://github.com/servo/servo/pull/8449
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/120)
=> add 'sizes' atom

shared/Cargo.toml, shared/static_atom_list.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/122)
=> Add "error" to the static atoms.

Cargo.toml, examples/summarize-events/src/main.rs, src/atom/bench.rs, src/atom/mod.rs, src/namespace.rs
This is a breaking change:
* `Atom::from_slice(…)` needs to be replaced with `Atom::from(…)`
* `atom.as_slice().other_method()` with `atom.other_method()`
* `atom.as_slice()` in another auto-deref context with `&atom`
* `atom.as_slice()` in another context with either `&*atom` or `atom.as_ref()`
r? @asajeffrey
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/126)
=> Use conversion trait

Cargo.toml, src/atom/mod.rs
Add the following methods from AsciiExt:
```
pub fn is_ascii(&self) -> bool;
pub fn to_ascii_uppercase(&self) -> Atom;
pub fn to_ascii_lowercase(&self) -> Atom;
pub fn eq_ignore_ascii_case(&self, other: &Self) -> bool;
```
We can't implement AsciiExt in full because it requires mutable access.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/134)
=> Add non-mutating AsciiExt methods to Atom.

Cargo.toml, src/static_atom_list.rs
related to servo issue : https://github.com/servo/servo/issues/10491
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/148)
=> add dirname atom for HTMLInputElement attribute

src/atom/mod.rs
This is already used by rust-selectors for its Bloom filter, and is
implemented there by accessing the data field directly.
Also, in a Gecko-based Atom implementation, the implementation will need to
be different, so it's better to have it here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/149)
=> Define Atom::get_hash().

Cargo.toml, src/atom/mod.rs, src/lib.rs, src/namespace.rs, src/static_atom_list.rs
I have a Servo branch that introduces an atom crate for geckolib that is semantically compatible with string-cache but backed by gecko atoms.
I needed to tweak a few things though, so here are the changes required in string-cache.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/155)
=> Tweak string-cache to be compatible with the gecko-atom override

src/static_atom_list.rs
Required for [onstatechange](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#service-worker-onstatechange-attribute) on Service Workers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/158)
=> add onstatechange to static_atom_list

build.rs, examples/summarize-events/src/main.rs, src/atom/mod.rs
r? @nox
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/160)
=> Rename Atom::data to unsafe_data and hide it in docs.

Cargo.toml, src/atom/mod.rs, src/namespace.rs
This is part of the changes proposed at https://github.com/servo/servo/pull/12391#issuecomment-232183942
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/165)
=> Implement Default and PartialEq<String>.

Cargo.toml, src/atom/mod.rs, src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/167)
=> Drop flags are dead, long live MIR!

src/atom/mod.rs
This is a big deal if you're putting atoms inside a btreeset since it does a lot of cmp operations.
It's more unsafe, but
1. the only thing that constructs `Inline` atoms should be the `string-cache` code (which I've been utilising fairly heavily)
2. if `string-cache` code *isn't* the only thing constructing atoms, `Dynamic` atoms are wildly unsafe since they contain pointers
3. since the creation of `Inline` atoms is only dependent on length of string (not content) you can exhaustively check correctness just by inlining and derefing strings from `"a"` to `"aaaaaaa"`. I can add an explicit test for this if you like.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/175)
=> Make cmp massively faster for inline atoms

src/atom/mod.rs
Testable on 64-bit Linux with:
```
rustup target add i686-unknown-linux-gnu
cargo test --target i686-unknown-linux-gnu
```
(or similarly on anther 64-bit platforms), assuming a linker and libc for this target are available on the system.
Leaving #162 open to add CI for this. (Unfortunately Travis doesn’t use rustup out of the box.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/176)
=> Make tests pass on a 32-bit system.

examples/summarize-events/src/main.rs
Not sure how 0.3 passed Travis without this…
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/181)
=> Fix examples build

.travis.yml, Cargo.toml, README.md, src/atom.rs, src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/182)
=> Update serde to 0.9

Cargo.toml, src/atom.rs, src/lib.rs, string-cache-codegen/Cargo.toml, string-cache-codegen/lib.rs
This allows us to get rid of the extra hashing overhead every time we check the
bloom filter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/183)
=> Expose the precomputed hash using a trait so that I can use it from rust-selectors.

Cargo.toml, src/atom.rs
* Use `From<String> for Atom`
* Use the fast path with non-letters too
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/186)
=> Make to_ascii_{upper,lower}case more efficent.

Cargo.toml, src/atom.rs
Hi there!
I was just thinking the other day about how much I really didn't want to write a string interner and lo-and-behold one already exists! And it works!
This is just a really quick PR to update to stable `serde 1.0`. I could write a test to confirm items are deserialised to the interned value rather than allocating but that doesn't seem to be a thing that's done in other tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/187)
=> Update to serde 1.0

Cargo.toml, src/atom.rs
Needed to do more complex stuff in selectors with local names and namespace
urls.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/194)
=> Implement From<&Atom> for Atom.

.travis.yml, Cargo.toml, README.md, src/atom.rs, src/lib.rs
The heapsize crate is being deprecated in favour of the malloc_size_of
crate within Servo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/196)
=> Remove `heapsize` dependency.

string-cache-codegen/lib.rs
This PR provides functionality to add documentation to the macros created using `string_cache_codegen`.
It also copies the example from the README to the crate root docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/199)
=> Allow the generated macros to have documentation

Cargo.toml
Because the original debug_unreachable is abandoned and doesn't work correctly in modern Rust.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/206)
=> Switch to fork of debug_unreachable

string-cache-codegen/Cargo.toml
This is useful for cargo minimal version builds. `phf_generator` in versions before 0.7.22 depended on rand 0.3 which itself depended on libc 0.1.1 that no longer compiles with the newest Rust version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/218)
=> Bump phf_generator generator version to 0.7.22

Cargo.toml, src/atom.rs, tests/small-stack.rs
Fix https://github.com/servo/html5ever/issues/393
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/227)
=> Fix initializing the global hash map with a small stack

.travis.yml
This ensures that we test against Rust 1.36 in CI on all builds. This is very helpful documentation for downstream maintainers, as it quickly helps us figure out what version of Rust is supported by the library, and highlights changes to the minimum supported version during code review.
Closes #228.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/229)
=> Pin rustc version in .travis.yml

.travis.yml, Cargo.toml, src/trivial_impls.rs
This crate (and deps) takes around 8s to compile on my machine. I checked and this is mostly serde, and without it, a full rebuild takes only 0.5s (again, on my machine).
Many users of the crate will need serde, but some will not (e.g. I don't), and it's nice to get that compile time back for those that don't. It's on by default, for compatibility reasons, because default seems reasonable, and because I don't really care so long as I can disable it.
I've named the feature `serde_support` instead of just `serde` in case you ever need to enable other crates or dep feature based on this (but perhaps I'm wrong and this would be possible anyway).
I have tested locally, and added a CI smoke test to ensure it compiles without serde, but we don't run tests with out it (there are no serde-specific …
=> Make serde dependency optional

integration-tests/src/lib.rs, src/atom.rs
This methods returns a new static Atom, or None if the provided string is not present in the static table. This is an optimization when using this library to speed up matching against a large table of static atoms, as it allows to skip locking the global table and inserting the new string when the match is going to fail anyway.
I'm not too sure about the name of the method but nothing better comes to mind right now, and same goes for the specifics of the implementation (I moved the hash calculation to a private method to limit code duplication but it's only three lines so it's probably not that important, plus returning the Hashes in Result::Err seems dubious)
=> Add an Atom::try_static method

.github/workflows/ci.yml
This is required by new versions of the `instant` crate, which `parking_lot` depends upon.
=> Update MSRV to 1.38.0.

src/trivial_impls.rs
This PR implements a simple custom `de::Visitor` for `Atom`, which allows for deserializing without unnecessary round-trips through a `String`.
=> Use a custom Visitor in Deserialize

Cargo.toml, integration-tests/Cargo.toml, string-cache-codegen/Cargo.toml
This updates to the latest versions of the rand and phf crates. The real point is updating the transitive dependency on 'rand', to help keep build times under control in consumers of this library that are already using the newer version.
=> Update phf, rand dependencies

.github/workflows/ci.yml, Cargo.toml
parking_lot 0.11 was using parking_lot_core 0.8 which was creating a wasm export when targeting wasm: https://github.com/Amanieu/parking_lot/issues/269
This bumps to parking_lot 0.12, which uses parking_lot_core 0.9 which doesn't have the issue where it creates the wasm export.
=> fix: bump parking_lot to 0.12 in order to not create wasm export

Cargo.toml, src/dynamic_set.rs
Nowadays I think it's generally preferred to use `once_cell` over `lazy_static`.
=> Replace lazy_static with once_cell

src/atom.rs, src/dynamic_set.rs
Background:
I'm working a concurrent program using [swc](https://github.com/swc-project/swc) to parse files in parallel. [swc](https://github.com/swc-project/swc) uses `string-cache`.
I have found the global mutex in the dynamic set being the major performance bottleneck for our application. Using instruments as the profiler, we can see that `string-cache` contributes to 11.4% (9.6s) of the time:
By switch to a a bucket level mutex (this PR), `string-cache` drops to 1.6% (1.04s) of the time: 
----
For this PR, can I kindly ask for a code review even if this PR cannot be merged due to any kind of circumstances, so I can safely patch my application with a fork, or help me polish this so everyone using swc can benefit from this PR.
Thank you all in advance. 🍻
=> feat: use bucket mutex instead of global mutex for dynamic set

src/atom.rs
Tiny nit. Fixes a misspelling in a comment.
=> Fix comment typo

Cargo.toml
This will allow dependent packages to pick up improvements to mutex performance.
=> Bump version to 0.8.5

src/trivial_impls.rs
#266 caused a breaking change (see #271) in 0.8.5 (which was yanked).
This PR fixes #271 / will allow publishing new versions (so #268 can make it out).
I've just started learning Rust, haven't been able to 100% wrap my head around the issue.
The breaking change manifesting in the "browserlist-rs" crate:
```rust
error[E0283]: type annotations needed
--> {.. snip ..}\browserslist-rs-0.12.3\src\data\caniuse.rs:91:35
|
91 |     let chrome = CANIUSE_BROWSERS.get(&"chrome".into()).unwrap();
|                                   ^^^ ---------------- type must be known at this point
|                                   |
|                                   cannot infer type of the type parameter `Q` declared on the associated function `get`
|
= note: multiple `impl`s satisfying …
```
=> Revert trivial impl of Borrow<str> for Atom

integration-tests/src/common-usage.rs, integration-tests/src/lib.rs
As a response to #271, added tests with common usage.
I modified the project structure, so I could make use of the canonical (according to [the docs](https://doc.rust-lang.org/book/ch11-03-test-organization.html)) "external tests" support.
I'm not familiar with the nitty gritty and ramifications of this change, so absolutely looking for guidance/advice/instructions.
Concerns I'm aware of:
1. Integration tests can't have their own `build.rs`, so I moved it to be under the main crate. Does it matter that it'll run with `cargo build` now, where previously it would only run with `cargo test`
2. The `bench.rs` is apparently only supported in nightly? It didn't run with `cargo test`. Is it in use at all? How can I make sure that it runs properly under the new structure (with the same command …
=> test: add common dependents' usage

Cargo.toml
The breaking change was reverted in #272.
=> Publish 0.8.6.

src/dynamic_set.rs
Fix needed after #268 
The fix is only for debug_assert correctness. There's no functional effect.
i.e. version 0.8.6 might cause debug tests to fail, but it isn't a (functionally) breaking change.
**Explanation**
Moving the lock to be per-bucket changed the `DYNAMIC_SET`'s API so that it doesn't need to be locked (i.e. `DYANMIC_SET` is not wrapped with a `Mutex`).
The `Atom`'s `fn drop` changed from
```rust
fn drop(&mut self) {
if self.tag() == DYNAMIC_TAG {
let entry = self.unsafe_data.get() as *const Entry;
if unsafe { &*entry }.ref_count.fetch_sub(1, SeqCst) == 1 {
drop_slow(self)
}
}
// Out of line to guide inlining.
fn drop_slow<Static>(this: &mut Atom<Static>) {
DYNAMIC_SET
.lock()
.remove(this.unsafe_data.get() as *mut Entry);
}
}
```
to
```rust
impl<Static> Drop for Atom<Static> …
```
=> fix: move debug_assert check

.github/workflows/ci.yml, Cargo.toml, string-cache-codegen/Cargo.toml
phf bumped their MSRV to 1.60 https://github.com/rust-phf/rust-phf/compare/v0.10.1...v0.11.0 . I couldn't find a MSRV policy for this crate to know if that's acceptable or not.
=> Update phf to 0.11

src/atom.rs
Deref of an atom (e.g. `atom.to_string()`) which stores the string inline performs slicing with `&src[..len]`. `len` is guaranteed to be within bounds, as an inline atom is always 7 bytes or less, so this can be substituted with `src.get_unchecked(..len)`.
Removing this bounds check improves performance of deref-ing an inline atom by approx 30%.
There's a lot of noise in the benchmarks, but it also seems to slightly improve performance of deref-ing static and dynamic atoms too, presumably because it reduces the size of the `deref()` function.
NB There's no gain to making the same change in `From<Cow<'a, str>> for Atom<Static>` because the compiler already deduces no bounds check is required due to the `if len <= MAX_INLINE_LEN` conditional.
=> Faster deref of inline atoms

integration-tests/build.rs, integration-tests/src/bench.rs, integration-tests/src/lib.rs, src/atom.rs, string-cache-codegen/lib.rs
As mentioned in #276, current behavior is that short strings can be stored as static strings or inline. This adds an overhead for interning short strings, as they need to be hashed and compared to possible matches in the static set.
This PR changes the behavior to always store strings of 7 bytes or less inline.
This greatly improves the performance of interning short strings - approx 250% speedup, depending on length of the string.
The benchmarks in this repo show no apparent negative effect on any other operations (though there's a lot of noise in the benchmarks).
This PR does not involve any breaking changes.
Even though interning short static atoms is very fast anyway, I imagine this change will translate to a significant real-world performance improvement for some use cases. For …
=> Prefer inline representation over static

.github/workflows/ci.yml
This is required by the latest version of syn, which is a dependency. Our CI is broken until we merge this.
=> Update MSRV to 1.61.

src/atom.rs
In this function you use the unsafe keyword for almost the entrie function body. 
We need to mark unsafe operations more precisely using unsafe keyword. Keeping unsafe blocks small can bring many benefits. For example, when mistakes happen, we can locate any errors related to memory safety within an unsafe block. This is the balance between Safe and Unsafe Rust. The separation is designed to make using Safe Rust as ergonomic as possible, but requires extra effort and care when writing Unsafe Rust.
Hope this PR can help you.
Best regards.
**References**
https://doc.rust-lang.org/nomicon/safe-unsafe-meaning.html
https://doc.rust-lang.org/book/ch19-01-unsafe-rust.html
=> The scope of the unsafe block can be appropriately reduced

string-cache-codegen/Cargo.toml
Publishes changes in revision d9e888f2f61d43c1868849a506104ee02d79027c needed for https://github.com/servo/html5ever/issues/573
Changes are SemVer patch increase. 
Hyrum's versioning might differ if something depended on random iteration order. Might not be important
=> Publish 0.5.4 string cache codegen

.github/workflows/ci.yml, Cargo.toml, src/atom.rs
Now that [malloc_size_of](https://github.com/servo/malloc_size_of) is published to crates.io we are moving the trait implementations of [MallocSizeOf](https://docs.rs/malloc_size_of/latest/malloc_size_of/trait.MallocSizeOf.html) and related traits into the crates that define the types. This will avoid the situation where depending on `malloc_size_of` pulls in a large number of dependencies.
This PR adds the implementation of `MallocSizeOf` to the `string-cache` crate.
=> Implement `MallocSizeOf` for `Atom`

Cargo.toml, README.md, integration-tests/Cargo.toml, src/lib.rs, string-cache-codegen/Cargo.toml, string-cache-codegen/lib.rs
It is not clear to me whether this is a breaking change. I bumped the version of the crates for now.
=> Update phf to 0.13

integration-tests/Cargo.toml, string-cache-codegen/lib.rs
This means that `local_name!(html)` will work as well as `local_name!("html")`.
If the atom value is something like `foo-bar` then `local_name!("foo-bar")` will work but `local_name!(foo-bar)` wont because `foo-bar` is not a valid `ident`.
=> Make macros accept idents where atom value is a valid ident
