servo/string-cache

- Cargo.toml
- macros/src/atom/mod.rs
- src/lib.rs
Not yet nightly, but can be merged without breaking Nightly users.
<s>Needs https://github.com/sfackler/rust-phf/pull/45 to build on the given rustc version</s>
> Update to rustc 1.0.0-dev (80627cd3c 2015-02-07 12:01:31 +0000)

- Cargo.toml
- plugin/src/lib.rs
- src/atom/mod.rs
- src/lib.rs
r? @mbrubeck -- this has a superset of #66
> Rustup and switch back to SipHash

- .travis.yml
- Cargo.toml
- examples/summarize-events/Cargo.toml
- examples/summarize-events/src/main.rs
- src/atom/mod.rs
- src/event.rs
- src/lib.rs
r=@glennw on the first two commits (#41)
r? @Manishearth for "Un-bitrot …"
> Event logging tools & fixes

- src/lib.rs
- src/namespace.rs
Brings us to rustc 1.0.0-nightly (52c74e63d 2015-01-29 22:54:19 +0000)
> Fix warnings

- examples/summarize-events/src/main.rs
- plugin/src/atom/mod.rs
- shared/repr.rs
- src/atom/bench.rs
- src/atom/mod.rs
- src/lib.rs
> Upgrade to rustc 1.0.0-nightly (123a754cb 2015-03-24) (built 2015-03-25)

- shared/repr.rs
- src/atom/mod.rs
> Fix compilation with latest Rust

- src/atom/mod.rs
> Allow Atom Deref to &str

- .gitignore
- Cargo.toml
- src/atom/mod.rs
Depends on https://github.com/sfackler/rust-phf/pull/55 being merged and published on crates.io.
> Upgrade phf. Fix #80.

- src/atom/mod.rs
- src/lib.rs
> Minor changes for new Rust.

- src/atom/mod.rs
https://github.com/servo/servo/pull/6555#issuecomment-118786436
> Implement AsRef<str> for Atom

- Cargo.toml
- src/atom/mod.rs
- src/lib.rs
> Add support for serialization via `serde`

- Cargo.toml
- src/atom/mod.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/97)
> Fix #[cfg(feature = "unstable")] syntax

- plugin/Cargo.toml
- plugin/src/atom/mod.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/100)
> Upgrade to rustc 1.3.0-nightly (8d432fbf1 2015-07-29)

- Cargo.toml
- build.rs
- shared/Cargo.toml
- shared/build.rs
r? @mbrubeck
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/102)
> Fix cross-compilation.

- Cargo.toml
r? @SimonSapin
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/104)
> Upgrade serde to pick up bincode support

- shared/static_atom_list.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/108)
> Add missing Ruby elements "rb" and "rtc"

- Cargo.toml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/112)
> Bump serde

- Cargo.toml
- plugin/Cargo.toml
- shared/Cargo.toml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/114)
> Bump crates

- Cargo.toml
- plugin/Cargo.toml
- shared/Cargo.toml
Version bump for https://github.com/servo/string-cache/pull/115.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/116)
> Version bump.

- shared/Cargo.toml
After completing #117, I bumped string_cache, but I should have bumped
string_cache_shared
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/118)
> Bump string_cache_shared

- plugin/Cargo.toml
- plugin/src/atom/mod.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/119)
> Rustup to rustc 1.6.0-nightly (5b4986fa5 2015-11-08)

- src/static_atom_list.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/128)
> Add "novalidate" to atom list.

- Cargo.toml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/129)
> Bump the version number.

- src/static_atom_list.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/130)
> Add formnovalidate to atom list

- Cargo.toml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/131)
> Bump version number to v0.2.2

- Cargo.toml
- src/static_atom_list.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/132)
> More static atoms!

- Cargo.toml
- src/static_atom_list.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/133)
> Add invalid to the list and bump version number

- Cargo.toml
- src/namespace.rs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/138)
> Derive HeapSizeOf for QualName

- src/static_atom_list.rs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/139)
> Add preload to static list.

- Cargo.toml
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/140)
> Version bump to 0.2.8

- src/atom/mod.rs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/144)
> Allow to retrieve the heap size of the dynamic string cache

- .travis.yml
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/145)
> Test on OS X through Travis

- src/atom/mod.rs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/143)
> Implement From<String> for Atom

- Cargo.toml
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/146)
> Bump to 0.2.10

- .travis.yml
- examples/event-log/src/main.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/151)
> Fix event log example

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/153)
> Release version 0.2.14

- Cargo.toml
- src/atom/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/154)
> Implement comparison between &Atom and &str.

- Cargo.toml
- src/static_atom_list.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/157)
> Add nonce to the atom list

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/159)
> Update to 0.2.18

- Cargo.toml
- src/atom/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/161)
> Store Box<str> instead of String

- .travis.yml
- Cargo.toml
- src/atom/mod.rs
- src/lib.rs
- src/namespace.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/166)
> Allow serde 0.8 and remove use of compiler plugins

- src/static_atom_list.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/170)
> Add activate string for Service Worker event

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/171)
> Version bump to 0.2.28

- Cargo.toml
- src/static_atom_list.rs
For https://github.com/servo/servo/issues/13313
@KiChjang
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/172)
> Add minlength to static_atom_list

- src/static_atom_list.rs
for servo/servo#11861
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/173)
> Add "referrerPolicy" to static_atom_list

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/174)
> Version bump to 0.2.30

- string-cache-codegen/Cargo.toml
- string-cache-codegen/lib.rs
r? @nox
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/180)
> Use the quote crate for code generation

- Cargo.toml
- src/atom.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/189)
> Avoid some allocations in to_ascii_{upper,lower}case

- Cargo.toml
- src/atom.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/190)
> Update to serde 1.0

- src/atom.rs
Fixes #191.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/192)
> Support big-endian platforms

- Cargo.toml
- src/atom.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/193)
> atom: Use the same hash everywhere.

- src/atom.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/198)
> Silence denied "unused import" warning on Nigthly

- src/atom.rs
- string-cache-codegen/lib.rs
Multiple changes
- Add documentation to types & methods in atom.rs
- Add ability to add documentation to generated types
What I'm trying to achieve with this is
1. Someone can look at this library and know how to use it without looking at the source code.
2. Someone who sees the generated types in another library (like html5ever) can just know they are interned strings and not worry too much about the interal details of the internment.
I hope it's useful :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/200)
> Add documentation, and the ability to generate documentation.

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/201)
> Update lazy_static to 1.0 and bump version

- Cargo.toml
- examples/simple.rs
- src/lib.rs
Specifically for internment without any static values.
I thought it would be useful to show a simple use of this library.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/204)
> Add a simple example of library use.

- string-cache-codegen/Cargo.toml
- string-cache-codegen/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/207)
> Update quote, proc-macro2 and bump version in codegen

- shared/Cargo.toml
- shared/LICENSE-APACHE
- shared/LICENSE-MIT
- string-cache-codegen/Cargo.toml
- string-cache-codegen/LICENSE-APACHE
- string-cache-codegen/LICENSE-MIT
Fixes #214.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/215)
> Add licenses to shared and codegen crates.

- src/atom.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/219)
> Replace ... operator with ..=

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/220)
> Update Travis CI URL

- src/atom.rs
- string-cache-codegen/Cargo.toml
- string-cache-codegen/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/string-cache/222)
> Update syn related dependencies to 1.0 and bump version

- .github/workflows/ci.yml
> Update MSRV to 1.40.0
